export declare const REGISTER_FEATURE = "REGISTER_FEATURE";
export declare const RECEIVE_FEATURE = "RECEIVE_FEATURE";
export declare const UNREGISTER_FEATURE = "UNREGISTER_FEATURE";
export declare const RECEIVE_FEATURES = "RECEIVE_FEATURES";
export declare const REGISTER_FEATURE_CALLBACK = "REGISTER_FEATURE_CALLBACK";
export declare const SET_FEATURE_INPUT_IN_PROGRESS = "SET_FEATURE_INPUT_IN_PROGRESS";
export declare const ENTITY_KIND = "root";
export declare const ENTITY_NAME = "features";
export declare const STORE_NAME = "feature-api";
//# sourceMappingURL=constants.d.ts.map